Script started on 2021-04-29 22:27:48-07:00
]777;notify;Command completed;exit]0;hpzhong@localhost:~/cse374/hw4]7;file://localhost.localdomain/home/hpzhong/cse374/hw4[hpzhong@localhost hw4]$ exitgcc -Wall -std=c11 -g -o countLetter countLetter.c
]777;notify;Command completed;gcc -Wall -std=c11 -g -o countLetter countLetter.c]0;hpzhong@localhost:~/cse374/hw4]7;file://localhost.localdomain/home/hpzhong/cse374/hw4[hpzhong@localhost hw4]$ gdb ./countLetter
GNU gdb (GDB) Red Hat Enterprise Linux 8.2-12.el8
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./countLetter...done.
(gdb) break 63
Breakpoint 1 at 0x400a8b: file countLetter.c, line 63.
(gdb) break 25
Breakpoint 2 at 0x400918: file countLetter.c, line 25.
(gdb) run a b[Ktest1 test2
Starting program: /home/hpzhong/cse374/hw4/countLetter a test1 test2
Missing separate debuginfos, use: yum debuginfo-install glibc-2.28-127.el8.x86_64

Breakpoint 1, main (argc=4, argv=0x7fffffffd438) at countLetter.c:63
63	  if (argc < 3) { // check number of arguments
(gdb) print arc[Kgc
$1 = 4
(gdb) print argv[0]
$2 = 0x7fffffffd7ec "/home/hpzhong/cse374/hw4/countLetter"
(gdb) print argv[1]
$3 = 0x7fffffffd811 "a"
(gdb) print argv[2]
$4 = 0x7fffffffd813 "test1"
(gdb) print arv[Kgv[3]
$5 = 0x7fffffffd819 "test2"
(gdb) continue
Continuing.

Breakpoint 2, readFile (filename=0x7fffffffd813 "test1") at countLetter.c:25
25	  file = fopen(filename, "r");
(gdb) backtrace
#0  readFile (filename=0x7fffffffd813 "test1") at countLetter.c:25
#1  0x0000000000400ba4 in main (argc=4, argv=0x7fffffffd438)
    at countLetter.c:84
(gdb) continue
Continuing.

Breakpoint 2, readFile (filename=0x7fffffffd819 "test2") at countLetter.c:25
25	  file = fopen(filename, "r");
(gdb) backtrace
#0  readFile (filename=0x7fffffffd819 "test2") at countLetter.c:25
#1  0x0000000000400ba4 in main (argc=4, argv=0x7fffffffd438)
    at countLetter.c:84
(gdb) continue
Continuing.
There are 11 "a"s in the textfiles
[Inferior 1 (process 5843) exited normally]
(gdb) quir[Kt
]777;notify;Command completed;gdb ./countLetter]0;hpzhong@localhost:~/cse374/hw4]7;file://localhost.localdomain/home/hpzhong/cse374/hw4[hpzhong@localhost hw4]$ exit
exit

Script done on 2021-04-29 22:29:23-07:00
