#!/bin/bash

# Peter Zhong
# CSE 374 HW3 Q1
# 4/26/2021

# This script takes an html and extracts all urls to CSE course websites.
# It stores these urls in a text file (name given by the user).

# check number of arguments
if [[ $# -lt 2 ]]
then
    echo 'Error: less than two arguments passed'
    exit 1
fi

# check input file
if [[ ! -f "$2" ]]
then
    echo 'Error: input file does not exist'
    exit 1
fi

# check output file
if [[ -f "$1" ]]
then
    echo 'Warning: replacing existing output file'
fi

# find all lines with http
grep 'http' "$2" > "$1"

# remove everything before http
sed -i 's/.*http/http/g' "$1"

# modify cse578 to include backslash
sed -i 's/cse578/cse578\//g' "$1"

# remove everthing after /' and adding 21sp
sed -i "s/\/'.*/\/21sp\//g" "$1"

# remove everything after /" and adding 21sp
sed -i 's/\/".*/\/21sp\//g' "$1"

# remove irrelevant urls
sed -i '/courses\//!d' "$1"
sed -i '/www/d' "$1"
sed -i '/csep/d' "$1"

# remove all the duplicating urls
sort "$1" | uniq > backup
cp backup "$1"
rm backup
exit 0
